blockchain:
  block:
    ticker: BLOCK
    rpchost: localhost
    rpcport: 41414
    rpcuser: user
    rpcpass: pass
    segwitactivated: 1584537260
    blocksdir: "/opt/blockchain/block/blocks"
    txlimit: 1000
    outputdir: "/opt/blockchain/go-chainloader-data"
  ltc:
    ticker: LTC
    rpchost: localhost
    rpcport: 9332
    rpcuser: user
    rpcpass: pass
    segwitactivated: 1494432226
    blocksdir: "/opt/blockchain/ltc/blocks"
    txlimit: 100
    outputdir: "/opt/blockchain/go-chainloader-data"
  btc:
    ticker: BTC
    rpchost: localhost
    rpcport: 8332
    rpcuser: user
    rpcpass: pass
    segwitactivated: 1503539857
    blocksdir: "/opt/blockchain/btc/blocks"
    txlimit: 100
    outputdir: "/opt/blockchain/go-chainloader-data"
