blockchain:
  block:
    rpchost: localhost
    rpcport: 41414
    rpcuser: test
    rpcpass: testAbc
    segwitactivated: 1584537260
  ltc:
    rpchost: localhost
    rpcport: 9332
    rpcuser: test
    rpcpass: testAbc
    segwitactivated: 1494432226
